//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avtori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avtori()
        {
            this.C_22Avtor_knigi = new HashSet<C_22Avtor_knigi>();
        }
    
        public int Id_avtora { get; set; }
        public string FIO_avtora { get; set; }
        public string dom_tel_avt { get; set; }
        public string kont_tel_avt { get; set; }
        public string sn_pasp_avt { get; set; }
        public Nullable<System.DateTime> data_pasp_avt { get; set; }
        public string mest_pasp_avt { get; set; }
        public string gorod_avtora { get; set; }
        public string adres_avtora { get; set; }
        public string INN_avtora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_22Avtor_knigi> C_22Avtor_knigi { get; set; }
    }
}
