//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C17_Studenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C17_Studenti()
        {
            this.C17Ochenki = new HashSet<C17Ochenki>();
        }
    
        public int Id_studenta { get; set; }
        public string Familia { get; set; }
        public string Imya { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Pol { get; set; }
        public string Ulicha { get; set; }
        public string Dom { get; set; }
        public string Kvartira { get; set; }
        public string Gruppa_zdorovya { get; set; }
        public string Uvlechenie { get; set; }
        public Nullable<int> Nomer_telefona { get; set; }
        public Nullable<int> Kurs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C17Ochenki> C17Ochenki { get; set; }
    }
}
