//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C17Ochenki
    {
        public Nullable<int> Id_studenta { get; set; }
        public int Id_predmeta { get; set; }
        public Nullable<int> Ochnka { get; set; }
    
        public virtual C17_Studenti C17_Studenti { get; set; }
        public virtual C17Predmeti C17Predmeti { get; set; }
    }
}
