//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C17Predmeti
    {
        public int Id_predmeta { get; set; }
        public string Nazvanie { get; set; }
        public string Prepodavatel { get; set; }
    
        public virtual C17Ochenki C17Ochenki { get; set; }
    }
}
