//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_18Postavka
    {
        public int ID_postavki { get; set; }
        public Nullable<int> ID_postavshika { get; set; }
        public Nullable<System.DateTime> Data_postuplenia { get; set; }
        public Nullable<int> ID_sklada { get; set; }
    
        public virtual C_18Postavshik C_18Postavshik { get; set; }
        public virtual C_18Sklad C_18Sklad { get; set; }
    }
}
