//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_18Postavshik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_18Postavshik()
        {
            this.C_18Postavka = new HashSet<C_18Postavka>();
        }
    
        public int ID_postavshika { get; set; }
        public string Еmail { get; set; }
        public string Familia_predstavitelya { get; set; }
        public string Imya_predstavitelya { get; set; }
        public string Onchestvo_predstavitelya { get; set; }
        public string Adres { get; set; }
        public Nullable<int> Nomer_telefona { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_18Postavka> C_18Postavka { get; set; }
    }
}
