//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_18Hleb_izdelia
    {
        public int ID_hlebobulochnih_izdeliy { get; set; }
        public string Naimenovanie { get; set; }
        public Nullable<int> Stoimost { get; set; }
        public Nullable<int> ID_sklada { get; set; }
        public Nullable<int> ID_jurnala_prodj { get; set; }
    
        public virtual C_18Jurnal_prodaj C_18Jurnal_prodaj { get; set; }
        public virtual C_18Sklad C_18Sklad { get; set; }
    }
}
