//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_20Gruppa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_20Gruppa()
        {
            this.C_20Raspisanie = new HashSet<C_20Raspisanie>();
        }
    
        public int Id_Gruppi { get; set; }
        public string Nazvanie_gr { get; set; }
        public Nullable<int> Kolichestvo_stud { get; set; }
        public Nullable<int> Smena { get; set; }
        public Nullable<int> Kurs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_20Raspisanie> C_20Raspisanie { get; set; }
    }
}
