//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_20Raspisanie
    {
        public int Id_Raspisania { get; set; }
        public Nullable<int> Id_Predmeti { get; set; }
        public Nullable<int> Id_Dni_nedeli { get; set; }
        public Nullable<int> Id_Gruppi { get; set; }
        public Nullable<int> Id_Auditoria { get; set; }
        public Nullable<int> Id_Prepodavatelya { get; set; }
        public Nullable<int> Id_Nomer_pari { get; set; }
    
        public virtual C_20Auditorii C_20Auditorii { get; set; }
        public virtual C_20Dni_nedeli C_20Dni_nedeli { get; set; }
        public virtual C_20Gruppa C_20Gruppa { get; set; }
        public virtual C_20Nomer_P C_20Nomer_P { get; set; }
        public virtual C_20Predmeti C_20Predmeti { get; set; }
        public virtual C_20Prepodavateli C_20Prepodavateli { get; set; }
    }
}
