//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_20Auditorii
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_20Auditorii()
        {
            this.C_20Raspisanie = new HashSet<C_20Raspisanie>();
        }
    
        public int Id_Auditoria { get; set; }
        public Nullable<int> Id_Korpusa { get; set; }
        public Nullable<int> Kolichestvo_mest { get; set; }
        public string Nazvanie { get; set; }
    
        public virtual C_20Korpusa C_20Korpusa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_20Raspisanie> C_20Raspisanie { get; set; }
    }
}
