//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_22Knigi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_22Knigi()
        {
            this.C_22_Avtori_knig = new HashSet<C_22_Avtori_knig>();
        }
    
        public int Kod_knigi { get; set; }
        public string Nazvanie { get; set; }
        public string God_izdania { get; set; }
        public string Mesto_hranenia { get; set; }
        public Nullable<int> Kod_razdela { get; set; }
        public Nullable<int> Kod_izdatelstva { get; set; }
        public Nullable<int> Kol_shtuk_na_abon { get; set; }
        public Nullable<int> Kol_shtuk_v_chit_zale { get; set; }
        public Nullable<int> Cena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_22_Avtori_knig> C_22_Avtori_knig { get; set; }
        public virtual C_22Izdatelstva C_22Izdatelstva { get; set; }
        public virtual C_22Razdel C_22Razdel { get; set; }
    }
}
