//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_22Avtor_knigi
    {
        public int Id_avt_knigi { get; set; }
        public Nullable<int> Id_avtora { get; set; }
        public Nullable<decimal> gonorar_avtora { get; set; }
        public Nullable<int> poryadkovii_nomer { get; set; }
        public Nullable<int> ISBN { get; set; }
    
        public virtual Avtori Avtori { get; set; }
        public virtual Knigi Knigi { get; set; }
    }
}
