//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_23Podpischiki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_23Podpischiki()
        {
            this.C_23Podpiska = new HashSet<C_23Podpiska>();
        }
    
        public int Kod_podpischika { get; set; }
        public string FIO { get; set; }
        public Nullable<int> Kod_ulici { get; set; }
        public string Dom_kvartira { get; set; }
    
        public virtual C_23Ulica C_23Ulica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_23Podpiska> C_23Podpiska { get; set; }
    }
}
