//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_23Podpiska
    {
        public int Nomer_v_kvitancii { get; set; }
        public Nullable<int> Kod_podpischika { get; set; }
        public Nullable<int> Kod_izdania { get; set; }
        public Nullable<int> Kol_vo_mesyacev { get; set; }
        public Nullable<System.DateTime> Data_podpiski { get; set; }
    
        public virtual C_23Izdanie C_23Izdanie { get; set; }
        public virtual C_23Podpischiki C_23Podpischiki { get; set; }
    }
}
