//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_23Izdanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_23Izdanie()
        {
            this.C_23Podpiska = new HashSet<C_23Podpiska>();
        }
    
        public int Kod_izdania { get; set; }
        public Nullable<int> Indeks_izdania { get; set; }
        public string Nazvanie { get; set; }
        public Nullable<int> Stoimost_za_mesyac { get; set; }
        public Nullable<int> Kod_tipa_izdania { get; set; }
    
        public virtual C_23Tip_izdania C_23Tip_izdania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_23Podpiska> C_23Podpiska { get; set; }
    }
}
