//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_24Zakazi
    {
        public int Kod_zakaza { get; set; }
        public Nullable<int> Nomer_nakladnoy { get; set; }
        public Nullable<System.DateTime> Data_zakaza { get; set; }
        public Nullable<System.DateTime> Data_otgruzki { get; set; }
        public Nullable<int> Kod_poluchteLya { get; set; }
    
        public virtual C_24Poluchateli C_24Poluchateli { get; set; }
    }
}
