//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_25P1
    {
        public int Kod_poluch { get; set; }
        public string Organizaciya { get; set; }
        public Nullable<int> Kod_goroda { get; set; }
        public string Adres { get; set; }
        public string Tel { get; set; }
    }
}
