//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_26Prod_tovar
    {
        public int Kod_zakaza { get; set; }
        public Nullable<int> Kod_tovara { get; set; }
        public Nullable<int> Kolich_prod_tovara { get; set; }
    
        public virtual C_26Tovari C_26Tovari { get; set; }
    }
}
