//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_27Prodaji_mashini
    {
        public int Id_prodaj { get; set; }
        public Nullable<int> Kol_prod_mashin { get; set; }
        public Nullable<int> Id_perechna_avto { get; set; }
    
        public virtual C_27Katalog_machin C_27Katalog_machin { get; set; }
    }
}
