//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_27Katalog_machin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_27Katalog_machin()
        {
            this.C_27Prodaji_mashini = new HashSet<C_27Prodaji_mashini>();
        }
    
        public int Id_perechna_avto { get; set; }
        public string Marka { get; set; }
        public string Komplektacia { get; set; }
        public Nullable<int> Stoimost { get; set; }
        public Nullable<int> Seriniy_nomer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_27Prodaji_mashini> C_27Prodaji_mashini { get; set; }
    }
}
