//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_29Postavka
    {
        public int Id_postavki { get; set; }
        public Nullable<int> Kolichestvo_postavlyem_tovarov { get; set; }
        public Nullable<System.DateTime> Data_postavki { get; set; }
        public Nullable<int> Id_sklada { get; set; }
    
        public virtual C_29Sklad C_29Sklad { get; set; }
    }
}
