//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Jbrazovanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Jbrazovanie()
        {
            this.C_Sotrudniki = new HashSet<C_Sotrudniki>();
        }
    
        public int Kod_obrazovania { get; set; }
        public string Uchebnoe_zavedenie { get; set; }
        public string Naimenovanie { get; set; }
        public Nullable<System.DateTime> Data_vipuska { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Sotrudniki> C_Sotrudniki { get; set; }
    }
}
