//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Marshrut2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Marshrut2()
        {
            this.C_Vodeteli_marshruta = new HashSet<C_Vodeteli_marshruta>();
        }
    
        public int Kod_marshruta { get; set; }
        public Nullable<int> Nomer { get; set; }
        public Nullable<int> Nachalnay_ostanovka { get; set; }
        public Nullable<int> Konechnay_ostanovka { get; set; }
        public string Vremay_puti { get; set; }
    
        public virtual C_Ostanovki C_Ostanovki { get; set; }
        public virtual C_Ostanovki C_Ostanovki1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Vodeteli_marshruta> C_Vodeteli_marshruta { get; set; }
    }
}
