//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Raspisanie
    {
        public int Kod_raspisania { get; set; }
        public Nullable<int> Kod_dney_nedeli { get; set; }
        public Nullable<int> Kod_vremya_priema { get; set; }
        public Nullable<int> Kod_kabineta { get; set; }
        public Nullable<int> kod_vrachey { get; set; }
    
        public virtual C_Dni_nedeli C_Dni_nedeli { get; set; }
        public virtual C_Kabineti C_Kabineti { get; set; }
        public virtual C_Vrachi C_Vrachi { get; set; }
        public virtual C_Vremya_priema C_Vremya_priema { get; set; }
    }
}
