//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Roditeli
    {
        public int Kod_roditeley { get; set; }
        public Nullable<int> Kod_sotrudnika { get; set; }
        public Nullable<int> Kod_rebenka { get; set; }
    
        public virtual C_Deti_sotrudnikov C_Deti_sotrudnikov { get; set; }
        public virtual C_Sotrudniki C_Sotrudniki { get; set; }
    }
}
