//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Sotrudniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Sotrudniki()
        {
            this.C_Roditeli = new HashSet<C_Roditeli>();
        }
    
        public int Kod_sotrudnika { get; set; }
        public string Famelia { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public string Status_sotrudnika { get; set; }
        public string Pasportnie_dannie { get; set; }
        public string Adres_sotrudnika { get; set; }
        public Nullable<int> Dom_tel { get; set; }
        public string Pol_sotrudnika { get; set; }
        public Nullable<System.DateTime> Data_rojdenia { get; set; }
        public string Obrazovania { get; set; }
        public Nullable<int> Kod_doljnoti { get; set; }
        public Nullable<int> Kod_otdela { get; set; }
        public Nullable<System.DateTime> Data_postuplenia { get; set; }
        public string Status { get; set; }
        public Nullable<int> Kod_obrazovania { get; set; }
        public Nullable<int> Kod_statusa { get; set; }
    
        public virtual C_Doljnot C_Doljnot { get; set; }
        public virtual C_Jbrazovanie C_Jbrazovanie { get; set; }
        public virtual C_Otdeli C_Otdeli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Roditeli> C_Roditeli { get; set; }
        public virtual C_Status C_Status { get; set; }
    }
}
