//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Studenti
    {
        public int Id_studenta { get; set; }
        public string Famelia_studenta { get; set; }
        public string Imi_studenta { get; set; }
        public string Otchestvo_studenta { get; set; }
        public string Pasportnie_dannie_student { get; set; }
        public string Adres_studenta { get; set; }
        public Nullable<int> Domash_tel_studenta { get; set; }
        public string Sotoviy_tel_studenta { get; set; }
        public string Pol_studenta { get; set; }
        public Nullable<System.DateTime> Data_rojdenia_studenta { get; set; }
        public Nullable<System.DateTime> Data_postuplenia { get; set; }
        public Nullable<System.DateTime> Data_otchislenua { get; set; }
        public Nullable<int> id_gruppi { get; set; }
    
        public virtual Gruppi Gruppi { get; set; }
    }
}
