//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Voditeli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Voditeli()
        {
            this.C_Vodeteli_marshruta = new HashSet<C_Vodeteli_marshruta>();
        }
    
        public int Kod_voditelay { get; set; }
        public string Familiya { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public string Pasportnie_dannie { get; set; }
        public string Domashniy_adress { get; set; }
        public Nullable<int> Domashniy_telefon { get; set; }
        public Nullable<int> Sotoviy_telefon { get; set; }
        public Nullable<int> Kod_mashini { get; set; }
    
        public virtual C_Mashini C_Mashini { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Vodeteli_marshruta> C_Vodeteli_marshruta { get; set; }
    }
}
