//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Vodeteli_marshruta
    {
        public int Kod_vditelay_mar { get; set; }
        public Nullable<int> Kod_marshruta { get; set; }
        public Nullable<int> Kod_voditelay { get; set; }
    
        public virtual C_Marshrut2 C_Marshrut2 { get; set; }
        public virtual C_Voditeli C_Voditeli { get; set; }
    }
}
