//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Vrachi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Vrachi()
        {
            this.C_Raspisanie = new HashSet<C_Raspisanie>();
        }
    
        public int kod_vrachey { get; set; }
        public string Familiya { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public Nullable<int> Dom_tel { get; set; }
        public Nullable<int> Kod_dpec { get; set; }
        public Nullable<int> Kod_kategor { get; set; }
        public string Zakrep_uch { get; set; }
    
        public virtual C_Kadegoria C_Kadegoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Raspisanie> C_Raspisanie { get; set; }
        public virtual C_Specialnosti C_Specialnosti { get; set; }
    }
}
