//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gruppi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gruppi()
        {
            this.C_Studenti = new HashSet<C_Studenti>();
        }
    
        public int id_gruppi { get; set; }
        public string Nazvanie_gruppi { get; set; }
        public string Status_gruppi { get; set; }
        public Nullable<int> id_otdelenia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Studenti> C_Studenti { get; set; }
        public virtual Otdeleniya Otdeleniya { get; set; }
    }
}
