//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knigi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Knigi()
        {
            this.C_22Avtor_knigi = new HashSet<C_22Avtor_knigi>();
        }
    
        public int ISBN { get; set; }
        public Nullable<int> Id_kategorii { get; set; }
        public string nazvanie_knigi { get; set; }
        public Nullable<int> kolichestvo_stranic { get; set; }
        public string annotaciya { get; set; }
        public Nullable<int> tirag { get; set; }
        public Nullable<decimal> cena_exemplyara { get; set; }
        public string avtorskii_znak { get; set; }
        public Nullable<int> izdanie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_22Avtor_knigi> C_22Avtor_knigi { get; set; }
        public virtual Kategorii Kategorii { get; set; }
    }
}
