//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user41_dbEntities : DbContext
    {
        public user41_dbEntities()
            : base("name=user41_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_17Nov_pred> C_17Nov_pred { get; set; }
        public virtual DbSet<C_18Hleb_izdelia> C_18Hleb_izdelia { get; set; }
        public virtual DbSet<C_18Jurnal_prodaj> C_18Jurnal_prodaj { get; set; }
        public virtual DbSet<C_18Klient> C_18Klient { get; set; }
        public virtual DbSet<C_18Postavka> C_18Postavka { get; set; }
        public virtual DbSet<C_18Postavshik> C_18Postavshik { get; set; }
        public virtual DbSet<C_18Sklad> C_18Sklad { get; set; }
        public virtual DbSet<C_18Zakaz> C_18Zakaz { get; set; }
        public virtual DbSet<C_19Registracya_Polzovatelya> C_19Registracya_Polzovatelya { get; set; }
        public virtual DbSet<C_20Auditorii> C_20Auditorii { get; set; }
        public virtual DbSet<C_20Dni_nedeli> C_20Dni_nedeli { get; set; }
        public virtual DbSet<C_20Gruppa> C_20Gruppa { get; set; }
        public virtual DbSet<C_20Korpusa> C_20Korpusa { get; set; }
        public virtual DbSet<C_20Nomer_P> C_20Nomer_P { get; set; }
        public virtual DbSet<C_20Predmeti> C_20Predmeti { get; set; }
        public virtual DbSet<C_20Prepodavateli> C_20Prepodavateli { get; set; }
        public virtual DbSet<C_20Raspisanie> C_20Raspisanie { get; set; }
        public virtual DbSet<C_20Uchebniy_plan> C_20Uchebniy_plan { get; set; }
        public virtual DbSet<C_21Poseshaermost> C_21Poseshaermost { get; set; }
        public virtual DbSet<C_22_Avtori_knig> C_22_Avtori_knig { get; set; }
        public virtual DbSet<C_22Avtor_knigi> C_22Avtor_knigi { get; set; }
        public virtual DbSet<C_22Izdatelstva> C_22Izdatelstva { get; set; }
        public virtual DbSet<C_22Knigi> C_22Knigi { get; set; }
        public virtual DbSet<C_22Razdel> C_22Razdel { get; set; }
        public virtual DbSet<C_23Izdanie> C_23Izdanie { get; set; }
        public virtual DbSet<C_23Podpischiki> C_23Podpischiki { get; set; }
        public virtual DbSet<C_23Podpiska> C_23Podpiska { get; set; }
        public virtual DbSet<C_23Tip_izdania> C_23Tip_izdania { get; set; }
        public virtual DbSet<C_23Ulica> C_23Ulica { get; set; }
        public virtual DbSet<C_24Poluchateli> C_24Poluchateli { get; set; }
        public virtual DbSet<C_24Zakazi> C_24Zakazi { get; set; }
        public virtual DbSet<C_25P1> C_25P1 { get; set; }
        public virtual DbSet<C_26Prod_tovar> C_26Prod_tovar { get; set; }
        public virtual DbSet<C_26Tovari> C_26Tovari { get; set; }
        public virtual DbSet<C_27Katalog_machin> C_27Katalog_machin { get; set; }
        public virtual DbSet<C_27Prodaji_mashini> C_27Prodaji_mashini { get; set; }
        public virtual DbSet<C_28RegPol> C_28RegPol { get; set; }
        public virtual DbSet<C_29Postavka> C_29Postavka { get; set; }
        public virtual DbSet<C_29Sklad> C_29Sklad { get; set; }
        public virtual DbSet<C_Deti_sotrudnikov> C_Deti_sotrudnikov { get; set; }
        public virtual DbSet<C_Dni_nedeli> C_Dni_nedeli { get; set; }
        public virtual DbSet<C_Doljnot> C_Doljnot { get; set; }
        public virtual DbSet<C_Jbrazovanie> C_Jbrazovanie { get; set; }
        public virtual DbSet<C_Kabineti> C_Kabineti { get; set; }
        public virtual DbSet<C_Kadegoria> C_Kadegoria { get; set; }
        public virtual DbSet<C_Marshrut2> C_Marshrut2 { get; set; }
        public virtual DbSet<C_Mashini> C_Mashini { get; set; }
        public virtual DbSet<C_Ostanovki> C_Ostanovki { get; set; }
        public virtual DbSet<C_Otdeli> C_Otdeli { get; set; }
        public virtual DbSet<C_Raspisanie> C_Raspisanie { get; set; }
        public virtual DbSet<C_Roditeli> C_Roditeli { get; set; }
        public virtual DbSet<C_Sotrudniki> C_Sotrudniki { get; set; }
        public virtual DbSet<C_Specialnosti> C_Specialnosti { get; set; }
        public virtual DbSet<C_Status> C_Status { get; set; }
        public virtual DbSet<C_Studenti> C_Studenti { get; set; }
        public virtual DbSet<C_Vodeteli_marshruta> C_Vodeteli_marshruta { get; set; }
        public virtual DbSet<C_Voditeli> C_Voditeli { get; set; }
        public virtual DbSet<C_Vrachi> C_Vrachi { get; set; }
        public virtual DbSet<C_Vremya_priema> C_Vremya_priema { get; set; }
        public virtual DbSet<C17_Studenti> C17_Studenti { get; set; }
        public virtual DbSet<C17Predmeti> C17Predmeti { get; set; }
        public virtual DbSet<A_bank> A_bank { get; set; }
        public virtual DbSet<Avtori> Avtori { get; set; }
        public virtual DbSet<Gruppi> Gruppi { get; set; }
        public virtual DbSet<Kategorii> Kategorii { get; set; }
        public virtual DbSet<Knigi> Knigi { get; set; }
        public virtual DbSet<Manufacturer> Manufacturer { get; set; }
        public virtual DbSet<Otdeleniya> Otdeleniya { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<C_20register> C_20register { get; set; }
        public virtual DbSet<C17Ochenki> C17Ochenki { get; set; }
    }
}
